[package]
name = "nrt"
version = "0.0.1"
authors = ["Pengfei Zhang <zpfalpc23@gmail.com>"]

[dependencies]
parity-wasm = { git = "https://github.com/zhangpf/parity-wasm" }
lazy_static = "1.2.0"
llvm-sys = "70.0.0"

[dev-dependencies]
clap = "2.32.0"
