[package]
name = "nrt"
version = "0.0.1"
authors = ["Pengfei Zhang <zpfalpc23@gmail.com>"]


[[bin]]
name = "nrt-run-wasm"
path = "bin/nrt-run-wasm.rs"

[dependencies]
parity-wasm = "0.35.4"
lazy_static = "1.2.0"
llvm-sys = "70.0.1"
clap = "2.32.0"
